name: fiszker
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  fl_chart: ^0.3.4
  flutter: { sdk: flutter }
  flutter_bloc: ^1.0.0
  flutter_speed_dial: ^1.2.4
  optional: ^3.1.0
  path: ^1.6.4
  quiver: '>=2.0.0 <3.0.0'
  sqflite: ^1.1.7+2
  timeago: ^2.0.21
  tuple: ^1.0.3
  uuid: ^2.0.2

dev_dependencies:
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: true
