name: fiszker
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  fl_chart: ^0.6.3
  flutter: { sdk: flutter }
  flutter_bloc: ^3.1.0
  flutter_speed_dial: ^1.2.5
  optional: ^4.0.1
  path: ^1.6.4
  quiver: '>=2.0.0 <3.0.0'
  sqflite: ^1.2.0
  timeago: ^2.0.24
  tuple: ^1.0.3
  uuid: ^2.0.4

dev_dependencies:
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: true
